name: Deploy app
on:
  push:
    tags:        
      - '*' 
jobs: 
  deploy-app: 
    name: deploy app
    runs-on: ubuntu-latest
    steps:
    - name: configure enviroment
      uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: get flutter dependencies
      run: flutter pub get
    - name: Generate env file
      env:
        SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
        SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
      run: dart run .tool/env_service.dart
    - name: get node dependencies
      run: npm install
    - name: code analyze
      run: flutter analyze
    - name: build web app
      run: flutter build web
    - name: minimize assets
      run: npm run minimize
    - name: deploy to web
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project universo-flutter
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
